# Generated by Django 3.1.1 on 2020-11-18 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room_participants',
            name='user_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Creator.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_contact_number',
            name='user_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Creator.user'),
            preserve_default=False,
        ),
    ]
