# Generated by Django 3.1.1 on 2020-11-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0007_auto_20201118_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_schedule_pattern',
            name='event_id',
        ),
    ]
