# Generated by Django 3.1.1 on 2020-11-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0008_remove_event_schedule_pattern_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_schedule',
            name='event_schedule_pattern_id',
        ),
        migrations.RemoveField(
            model_name='student_schedule',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Event_Schedule_Pattern',
        ),
        migrations.DeleteModel(
            name='Student_Schedule',
        ),
    ]
