# Generated by Django 3.1.1 on 2020-11-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0009_auto_20201118_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Train_Skill',
        ),
    ]
