# Generated by Django 3.1.1 on 2020-11-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0011_event_schedule_pattern_event_train_skill_student_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_train_skill',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='event_train_skill',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='event_train_skill',
            name='training_intensity',
        ),
        migrations.RemoveField(
            model_name='student_schedule',
            name='event_schedule_pattern_id',
        ),
        migrations.RemoveField(
            model_name='student_schedule',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Event_Schedule_Pattern',
        ),
        migrations.DeleteModel(
            name='Event_Train_Skill',
        ),
        migrations.DeleteModel(
            name='Student_Schedule',
        ),
    ]
