# Generated by Django 3.1.1 on 2020-11-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0012_auto_20201118_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
