# Generated by Django 3.1.1 on 2020-11-18 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0013_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Creator.activity')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Event',
            },
            bases=('Creator.activity',),
        ),
        migrations.CreateModel(
            name='Event_Schedule_Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onMonday', models.BooleanField()),
                ('onTuesday', models.BooleanField()),
                ('onWednesDay', models.BooleanField()),
                ('onThursday', models.BooleanField()),
                ('onFriday', models.BooleanField()),
                ('onSaturday', models.BooleanField()),
                ('onSunday', models.BooleanField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.event')),
                ('schedule_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.schedule_type')),
            ],
            options={
                'db_table': 'Event_Schedule_Pattern',
            },
        ),
        migrations.CreateModel(
            name='Student_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_schedule_pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.event_schedule_pattern')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.student')),
            ],
            options={
                'db_table': 'Student_Schedule',
            },
        ),
        migrations.CreateModel(
            name='Event_Train_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_points', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.event')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.skill')),
                ('training_intensity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.skill_training_intensity')),
            ],
            options={
                'db_table': 'Event_Train_Skill',
            },
        ),
    ]
