# Generated by Django 3.1.1 on 2020-11-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0014_event_event_schedule_pattern_event_train_skill_student_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_report',
            name='reporter_student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_student_id', to='Creator.student'),
        ),
    ]
