# Generated by Django 3.1.1 on 2020-11-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0015_auto_20201118_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone_type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
