# Generated by Django 3.1.1 on 2020-11-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0018_job_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
