# Generated by Django 3.1.1 on 2020-11-18 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0020_auto_20201118_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_schedule',
            name='event_schedule_pattern_id',
        ),
        migrations.AddField(
            model_name='student_schedule',
            name='event_schedule_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Creator.event'),
        ),
    ]
