# Generated by Django 3.1.1 on 2020-11-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0021_auto_20201118_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_schedule',
            name='event_schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.event'),
        ),
    ]
