# Generated by Django 3.1.1 on 2020-11-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0022_auto_20201118_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Schedule',
        ),
    ]
