# Generated by Django 3.1.1 on 2020-11-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0023_delete_student_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.event')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.student')),
            ],
            options={
                'db_table': 'Student_Schedule',
            },
        ),
    ]
