# Generated by Django 3.1.1 on 2020-11-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0024_student_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Contact_Number',
            },
        ),
        migrations.DeleteModel(
            name='User_Contact_Number',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.ManyToManyField(to='Creator.Contact_Number'),
        ),
    ]
