# Generated by Django 3.1.1 on 2020-11-27 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0025_auto_20201127_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
