# Generated by Django 3.1.1 on 2020-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0026_auto_20201127_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
