# Generated by Django 3.1.1 on 2020-11-28 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0027_auto_20201127_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill_category',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
