# Generated by Django 3.1.1 on 2020-11-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0028_auto_20201128_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
