# Generated by Django 3.1.1 on 2020-11-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0029_student_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Contact_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'User_Contact_Number',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.DeleteModel(
            name='Contact_Number',
        ),
        migrations.AddField(
            model_name='user_contact_number',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.user'),
        ),
    ]
