# Generated by Django 3.1.1 on 2020-11-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0030_auto_20201128_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Contact_Number',
        ),
    ]
