# Generated by Django 3.1.1 on 2020-11-28 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0034_auto_20201128_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creator_community_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='activity_creator_id', to='Creator.community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='create_admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_admin_id_set', to='Creator.community'),
        ),
        migrations.AddField(
            model_name='community',
            name='delete_admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_admin_id_set', to='Creator.community'),
        ),
        migrations.AddField(
            model_name='community_improve_skill',
            name='community_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community_member',
            name='community_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_community_subscription',
            name='community_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
            preserve_default=False,
        ),
    ]
