# Generated by Django 3.1.1 on 2020-11-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0043_auto_20201128_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='create_admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_admin_id_set', to='Creator.community'),
        ),
        migrations.AddField(
            model_name='community',
            name='delete_admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delete_admin_id_set', to='Creator.community'),
        ),
        migrations.AddField(
            model_name='community_improve_skill',
            name='community_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
        ),
        migrations.AddField(
            model_name='community_member',
            name='community_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
        ),
        migrations.AddField(
            model_name='student_community_subscription',
            name='community_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
        ),
    ]
