# Generated by Django 3.1.1 on 2020-11-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0044_auto_20201128_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='creator_community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_creator_id', to='Creator.community'),
        ),
        migrations.AlterField(
            model_name='community_improve_skill',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
        ),
        migrations.AlterField(
            model_name='community_member',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
        ),
        migrations.AlterField(
            model_name='student_community_subscription',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.community'),
        ),
    ]
