# Generated by Django 3.1.1 on 2020-11-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0045_auto_20201128_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='status_admin_id',
        ),
    ]
