# Generated by Django 3.1.1 on 2020-11-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0046_remove_activity_status_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status_admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_status_admin', to='Creator.community'),
        ),
    ]
