# Generated by Django 3.1.1 on 2020-11-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0047_activity_status_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
