# Generated by Django 3.1.1 on 2020-11-29 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0048_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_possess_skill',
            name='date_acquired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
