# Generated by Django 3.1.1 on 2020-11-29 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0049_student_possess_skill_date_acquired'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='date_acquired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
