# Generated by Django 3.1.1 on 2020-11-29 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0050_milestone_date_acquired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='id',
        ),
        migrations.AddField(
            model_name='milestone',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
