# Generated by Django 3.1.1 on 2020-11-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0051_auto_20201129_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='milestone_datetime',
        ),
    ]
