# Generated by Django 3.1.1 on 2020-11-29 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0053_remove_milestone_type_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='name',
        ),
        migrations.AddField(
            model_name='milestone',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
