# Generated by Django 3.1.1 on 2020-11-29 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0054_auto_20201129_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
