# Generated by Django 3.1.1 on 2020-11-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0055_milestone_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='id',
        ),
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
