# Generated by Django 3.1.1 on 2020-11-29 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0058_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
