# Generated by Django 3.1.1 on 2020-11-30 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0059_student_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id_editable',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, null=True),
        ),
    ]
