# Generated by Django 3.1.1 on 2020-11-30 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0060_student_student_id_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id_editable',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
