# Generated by Django 3.1.1 on 2020-11-30 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0061_auto_20201130_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_possess_skill',
            name='points_to_next_level',
        ),
    ]
