# Generated by Django 3.1.1 on 2020-11-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0063_student_post_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_post_type',
            table='Student_Post_Type',
        ),
    ]
