# Generated by Django 3.1.1 on 2020-11-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0064_auto_20201130_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_post',
            name='post_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creator.student_post_type'),
        ),
    ]
