# Generated by Django 3.1.1 on 2020-11-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0065_student_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.student_post_type'),
        ),
    ]
