# Generated by Django 3.1.1 on 2020-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0068_post_report_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
