# Generated by Django 3.1.1 on 2020-12-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0069_student_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
