# Generated by Django 3.1.1 on 2020-12-08 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0072_activity_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='extendToOtherCommunities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='chat_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Creator.chat_room'),
        ),
        migrations.CreateModel(
            name='Activity_Target_Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.activity')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.department')),
            ],
            options={
                'db_table': 'Activity_Target_Department',
            },
        ),
    ]
