# Generated by Django 3.1.1 on 2020-12-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0074_auto_20201208_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
