# Generated by Django 3.1.1 on 2020-12-12 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0075_activity_rejection_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_created',
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
