# Generated by Django 3.1.1 on 2020-12-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0077_auto_20201212_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
